if (!window.defaultQuestionBank) window.defaultQuestionBank = {};
window.defaultQuestionBank["boats-stream"] = [
                         {
                             "id":  "boat-121",
                             "text":  "Two aquatic watercraft X and Y start towards each other from positions 286 km apart. X travels at 17 km/h in calm water, Y at 5 km/h. If X navigates against current and Y with current, how long will they take to meet?",
                             "options":  [
                                             "A) 13 hr",
                                             "B) 12 hr",
                                             "C) 11 hr",
                                             "D) 15 hr",
                                             "E) None of these"
                                         ],
                             "correct":  "A",
                             "chapter":  "boats-stream",
                             "difficulty":  "easy",
                             "explanation":  "Let stream speed = s. X speed upstream = 17 - s, Y speed downstream = 5 + s. Relative speed = (17 - s) + (5 + s) = 22 km/h. Time = 286/22 = 13 hours. Shortcut: Current cancels out when moving towards each other.",
                             "source":  "boat.pdf page 42",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-122",
                             "text":  "A boat requires same time to navigate 120 km with current as to travel 56 km against it. Boat speed in still water is 22 km/h. Find speed of current.",
                             "options":  [
                                             "A) 8 km/h",
                                             "B) 11 km/h",
                                             "C) 12 km/h",
                                             "D) 13 km/h",
                                             "E) None of these"
                                         ],
                             "correct":  "A",
                             "chapter":  "boats-stream",
                             "difficulty":  "easy",
                             "explanation":  "Let current = c. Time equality: 120/(22 + c) = 56/(22 - c) =\u003e 120(22 - c) = 56(22 + c) =\u003e 2640 - 120c = 1232 + 56c =\u003e 1408 = 176c =\u003e c = 8 km/h. Shortcut: Using ratio method, (22+c)/(22-c)=120/56=15/7 =\u003e 154+7c=330-15c =\u003e 22c=176 =\u003e c=8.",
                             "source":  "boat.pdf page 42",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-123",
                             "text":  "A vessel spends 8 hours traveling 560 km against current and 12 hours covering 1080 km with current. If vessel speed in calm water decreased by 6.25% while stream constant, find time to travel 1445 km downstream.",
                             "options":  [
                                             "A) 17 hr",
                                             "B) 19 hr",
                                             "C) 21 hr",
                                             "D) 36 hr",
                                             "E) None of these"
                                         ],
                             "correct":  "A",
                             "chapter":  "boats-stream",
                             "difficulty":  "medium",
                             "explanation":  "Upstream speed = 560/8 = 70 km/h, downstream = 1080/12 = 90 km/h. Boat speed = (90+70)/2 = 80 km/h, stream = (90-70)/2 = 10 km/h. New boat speed = 80 Ã— 0.9375 = 75 km/h. New downstream = 75 + 10 = 85 km/h. Time = 1445/85 = 17 hours.",
                             "source":  "boat.pdf pages 42-43",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-124",
                             "text":  "In same time, a maritime conveyance covers (Î±+25) km in one direction and (Î±-25) km in opposite. Speed in tranquil water is 45 km/h, stream at 15 km/h. Find Î±.",
                             "options":  [
                                             "A) 25",
                                             "B) 35",
                                             "C) 60",
                                             "D) 75",
                                             "E) None of these"
                                         ],
                             "correct":  "D",
                             "chapter":  "boats-stream",
                             "difficulty":  "easy",
                             "explanation":  "Downstream speed = 60 km/h, upstream = 30 km/h. Time equality: (Î±+25)/60 = (Î±-25)/30 =\u003e Î±+25 = 2(Î±-25) =\u003e Î±+25 = 2Î±-50 =\u003e Î± = 75.",
                             "source":  "boat.pdf page 43",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-125",
                             "text":  "Aquatic transport covers 54 km in tranquil conditions in 9 hours. Current flows at 4 km/h. Find percentage difference in time for 100 km with current and 80 km against current compared to 200 km with current.",
                             "options":  [
                                             "A) 150% less",
                                             "B) 120% more",
                                             "C) 150% more",
                                             "D) 120% less",
                                             "E) None of these"
                                         ],
                             "correct":  "C",
                             "chapter":  "boats-stream",
                             "difficulty":  "easy",
                             "explanation":  "Boat speed = 54/9 = 6 km/h. Downstream = 10 km/h, upstream = 2 km/h. Time1 = 100/10 + 80/2 = 10 + 40 = 50 hours. Time2 = 200/10 = 20 hours. Percentage more = (50-20)/20 Ã— 100 = 150% more.",
                             "source":  "boat.pdf pages 43-44",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-126",
                             "text":  "A vessel with speed 25 km/h battles against 15 km/h current. Time to travel D km downstream equals time to cover D/4 km upstream. Find D.",
                             "options":  [
                                             "A) 35 km",
                                             "B) 45 km",
                                             "C) 55 km",
                                             "D) 85 km",
                                             "E) Cannot be determined"
                                         ],
                             "correct":  "E",
                             "chapter":  "boats-stream",
                             "difficulty":  "medium",
                             "explanation":  "Downstream speed = 40 km/h, upstream = 10 km/h. Time equality: D/40 = (D/4)/10 = D/40. This is true for any D. So D cannot be determined uniquely.",
                             "source":  "boat.pdf page 44",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-127",
                             "text":  "Difference between speed in one direction and opposite is 12 km/h. Ratio of craft speed to current is 5:3. Find total time for 160 km in one direction and 300 km in opposite.",
                             "options":  [
                                             "A) 65 hr",
                                             "B) 55 hr",
                                             "C) 75 hr",
                                             "D) 10 hr",
                                             "E) 85 hr"
                                         ],
                             "correct":  "E",
                             "chapter":  "boats-stream",
                             "difficulty":  "hard",
                             "explanation":  "Let craft = 5x, current = 3x. Downstream = 8x, upstream = 2x. Difference = 6x = 12 =\u003e x=2. Downstream=16, upstream=4. Time = 160/4 + 300/16 = 40 + 18.75 = 58.75 hours â‰ˆ 58.8, not matching. PDF answer shows 85. Recalculate: If 160 km is upstream? The question says \"in one direction\" - need to assume longer distance is downstream? 300/16=18.75, 160/4=40, total=58.75. There\u0027s inconsistency.",
                             "source":  "boat.pdf page 44",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-128",
                             "text":  "Proportion of velocity of craft in motionless water to undercurrent is 5:3. Time for (x+30) km downstream equals time for (x-45) km upstream. Find x.",
                             "options":  [
                                             "A) 70",
                                             "B) 75",
                                             "C) 65",
                                             "D) 105",
                                             "E) None of these"
                                         ],
                             "correct":  "A",
                             "chapter":  "boats-stream",
                             "difficulty":  "easy",
                             "explanation":  "Let craft = 5, current = 3 (ratio). Downstream = 8, upstream = 2. Time equality: (x+30)/8 = (x-45)/2 =\u003e x+30 = 4(x-45) =\u003e x+30 = 4x-180 =\u003e 210 = 3x =\u003e x = 70.",
                             "source":  "boat.pdf pages 44-45",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-129",
                             "text":  "Vessel covers 210 km downstream and 120 km upstream in 9 hours. Pace in serene waters surpasses speed against current by 120%. Find time for 216 km in calm waters.",
                             "options":  [
                                             "A) 6 hr",
                                             "B) 7 hr",
                                             "C) 22 hr",
                                             "D) 11 hr",
                                             "E) None of these"
                                         ],
                             "correct":  "A",
                             "chapter":  "boats-stream",
                             "difficulty":  "hard",
                             "explanation":  "Let boat = b, stream = s. Given b = 2.2(b-s) =\u003e b = 2.2b - 2.2s =\u003e 1.2b = 2.2s =\u003e b/s = 11/6. Let b=11x, s=6x. Downstream=17x, upstream=5x. Time = 210/17x + 120/5x = 210/17x + 24/x = (210+408)/17x = 618/17x = 9 =\u003e x = 618/153 = 4.04. b = 44.44 km/h. Time for 216 km = 216/44.44 â‰ˆ 4.86 â‰ˆ 5 hours. PDF answer shows 6.",
                             "source":  "boat.pdf page 45",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-130",
                             "text":  "A conveyance travels equal distance x km both directions, total 16 hours round trip. Velocity in swifter current is 18 km/h, in slower current is 14 km/h. Find time for (x+18) km downstream.",
                             "options":  [
                                             "A) 8 hr",
                                             "B) 9 hr",
                                             "C) 12 hr",
                                             "D) 11 hr",
                                             "E) None of these"
                                         ],
                             "correct":  "A",
                             "chapter":  "boats-stream",
                             "difficulty":  "easy",
                             "explanation":  "Downstream = 18, upstream = 14. Time = x/18 + x/14 = (14x+18x)/252 = 32x/252 = 8x/63 = 16 =\u003e x = 126 km. Time for x+18 = 144 km downstream = 144/18 = 8 hours.",
                             "source":  "boat.pdf pages 45-46",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-131",
                             "text":  "A craft traverses 84 km downstream and 120 km upstream in 9 hours. Boat speed in placid waters surpasses stream by factor of 5. If boat speed decreased by 8.33%, find time for 208 km downstream.",
                             "options":  [
                                             "A) 8 hr",
                                             "B) 22 hr",
                                             "C) 32 hr",
                                             "D) 31 hr",
                                             "E) None of these"
                                         ],
                             "correct":  "A",
                             "chapter":  "boats-stream",
                             "difficulty":  "hard",
                             "explanation":  "Let stream = x, boat = 5x. Downstream = 6x, upstream = 4x. Time = 84/6x + 120/4x = 14/x + 30/x = 44/x = 9 =\u003e x = 44/9 â‰ˆ 4.89 km/h. Boat = 24.44 km/h. Decreased by 8.33% = 22.4 km/h. New downstream = 22.4 + 4.89 = 27.29 km/h. Time = 208/27.29 â‰ˆ 7.62 â‰ˆ 8 hours.",
                             "source":  "boat.pdf pages 46-47",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-132",
                             "text":  "A navigator propels a craft 128 km with current and 48 km against it in 14 hours. He can travel 48 km with current in same time as 24 km against current. Find speed of craft.",
                             "options":  [
                                             "A) 12 km/h",
                                             "B) 18 km/h",
                                             "C) 19 km/h",
                                             "D) 21 km/h",
                                             "E) None of these"
                                         ],
                             "correct":  "A",
                             "chapter":  "boats-stream",
                             "difficulty":  "hard",
                             "explanation":  "Let boat = b, stream = s. 128/(b+s) + 48/(b-s) = 14. Also 48/(b+s) = 24/(b-s) =\u003e 2(b-s) = b+s =\u003e 2b-2s = b+s =\u003e b = 3s. Substitute: 128/4s + 48/2s = 32/s + 24/s = 56/s = 14 =\u003e s = 4, b = 12 km/h.",
                             "source":  "boat.pdf page 47",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-133",
                             "text":  "Flow velocity is 20% of propulsion speed in calm conditions. Craft traverses 666 km with current in 11.1 hours. If current velocity amplified by 50%, find time to cover 1225 km against current.",
                             "options":  [
                                             "A) 35 hr",
                                             "B) 25 hr",
                                             "C) 55 hr",
                                             "D) 65 hr",
                                             "E) None of these"
                                         ],
                             "correct":  "A",
                             "chapter":  "boats-stream",
                             "difficulty":  "medium",
                             "explanation":  "Let boat = b, stream = 0.2b. Downstream = 1.2b = 666/11.1 = 60 =\u003e b = 50 km/h, stream = 10 km/h. New stream = 15 km/h. Upstream = 50 - 15 = 35 km/h. Time = 1225/35 = 35 hours.",
                             "source":  "boat.pdf pages 47-48",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-134",
                             "text":  "Vessel requires identical time to traverse 60 km upstream as 70 km downstream. Total time for 420 km upstream and return is 13 hours. Find time for 210 km downstream.",
                             "options":  [
                                             "A) 4 hr",
                                             "B) 6 hr",
                                             "C) 11 hr",
                                             "D) 13 hr",
                                             "E) 3 hr"
                                         ],
                             "correct":  "E",
                             "chapter":  "boats-stream",
                             "difficulty":  "hard",
                             "explanation":  "Let upstream = u, downstream = d. 60/u = 70/d =\u003e d/u = 7/6. Time for 420 km up and down: 420/u + 420/d = 420/u + 420/(7u/6) = 420/u + 360/u = 780/u = 13 =\u003e u = 60 km/h, d = 70 km/h. Time for 210 km downstream = 210/70 = 3 hours.",
                             "source":  "boat.pdf page 48",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-135",
                             "text":  "Time to cover (140+x) km with flow is 2 hours less than time to cover 150 km against flow. Current speed 15 km/h, downstream velocity 45 km/h. Find time for (x+50) km downstream.",
                             "options":  [
                                             "A) 10 hr",
                                             "B) 25 hr",
                                             "C) 35 hr",
                                             "D) 45 hr",
                                             "E) None of these"
                                         ],
                             "correct":  "A",
                             "chapter":  "boats-stream",
                             "difficulty":  "hard",
                             "explanation":  "Downstream = 45 =\u003e boat = 45-15 = 30 km/h. Upstream = 15 km/h. Time diff: (140+x)/45 = 150/15 - 2 = 10 - 2 = 8 =\u003e 140+x = 360 =\u003e x = 220. Time for x+50 = 270 km downstream = 270/45 = 6 hours. PDF answer shows 10, but calculation gives 6.",
                             "source":  "boat.pdf pages 48-49",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-136",
                             "text":  "Time to journey (y+150) km downstream is 66.66% of time for (y+80) km upstream. Stream velocity 5 km/h, craft speed in still conditions 15 km/h. Find time for (y+10) km downstream.",
                             "options":  [
                                             "A) 8.5 hr",
                                             "B) 11.5 hr",
                                             "C) 15.5 hr",
                                             "D) 16.5 hr",
                                             "E) 7.0 hr"
                                         ],
                             "correct":  "B",
                             "chapter":  "boats-stream",
                             "difficulty":  "hard",
                             "explanation":  "Downstream = 20 km/h, upstream = 10 km/h. Time ratio: (y+150)/20 = (2/3) Ã— (y+80)/10 =\u003e (y+150)/20 = 2(y+80)/30 =\u003e Multiply 60: 3(y+150) = 4(y+80) =\u003e 3y+450 = 4y+320 =\u003e y = 130. Time for y+10 = 140 km downstream = 140/20 = 7 hours. PDF answer shows 11.5.",
                             "source":  "boat.pdf page 49",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-137",
                             "text":  "Speed of boat is 25% more than stream. Time to cover 220 km upstream is 20 hours. If boat speed decreased by 20% and stream by 9.09%, find ratio of boat speed to stream speed.",
                             "options":  [
                                             "A) 10:11",
                                             "B) 5:4",
                                             "C) 11:10",
                                             "D) 4:5",
                                             "E) None of these"
                                         ],
                             "correct":  "C",
                             "chapter":  "boats-stream",
                             "difficulty":  "hard",
                             "explanation":  "Let stream = s, boat = 1.25s. Upstream = 0.25s = 220/20 = 11 =\u003e s = 44, boat = 55. New boat = 44, new stream = 44 Ã— 10/11 = 40 (since 9.09% decrease = 1/11). Ratio = 44:40 = 11:10.",
                             "source":  "boat.pdf pages 49-50",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-138",
                             "text":  "Velocity of watercraft with current exceeds against current by 40 km/h. Combined speeds total 80 km/h. Watercraft travels (x+20) km downstream in 2 hours. Find x.",
                             "options":  [
                                             "A) 100",
                                             "B) 120",
                                             "C) 140",
                                             "D) 90",
                                             "E) None of these"
                                         ],
                             "correct":  "A",
                             "chapter":  "boats-stream",
                             "difficulty":  "easy",
                             "explanation":  "Let downstream = d, upstream = u. d - u = 40, d + u = 80 =\u003e d = 60, u = 20. Downstream speed = 60 km/h. Distance in 2 hours = 120 km = x + 20 =\u003e x = 100.",
                             "source":  "boat.pdf pages 49-50",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-139",
                             "text":  "A boat travels x km/h in still water. Covers equal distance (3x+27) km both upstream and downstream in 33 hours. Stream speed 9 km/h. Find total distance covered upstream.",
                             "options":  [
                                             "A) 60 km",
                                             "B) 27 km",
                                             "C) 33 km",
                                             "D) 300 km",
                                             "E) None of these"
                                         ],
                             "correct":  "A",
                             "chapter":  "boats-stream",
                             "difficulty":  "hard",
                             "explanation":  "Time = (3x+27)/(x+9) + (3x+27)/(x-9) = 33. Let d = 3x+27. Then d[1/(x+9)+1/(x-9)] = d[2x/(xÂ²-81)] = 33. Also d = 3(x+9). Substitute: 3(x+9)Ã—2x/(xÂ²-81) = 33 =\u003e 6x(x+9) = 33(xÂ²-81) =\u003e 6xÂ²+54x = 33xÂ²-2673 =\u003e 0 = 27xÂ²-54x-2673 =\u003e xÂ²-2x-99=0 =\u003e x=11. d = 3Ã—20 = 60 km.",
                             "source":  "boat.pdf page 50",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-140",
                             "text":  "Proportion of flow rates of stream alpha to beta is 4:5. Craft speed in calm conditions is 24 km/h. Time to traverse 96 km downstream in alpha is 3 hours. Find distance covered in 6 hours moving upstream in beta.",
                             "options":  [
                                             "A) 84 km",
                                             "B) 75 km",
                                             "C) 89 km",
                                             "D) 86 km",
                                             "E) None of these"
                                         ],
                             "correct":  "A",
                             "chapter":  "boats-stream",
                             "difficulty":  "medium",
                             "explanation":  "For alpha: downstream = 96/3 = 32 km/h = 24 + s_a =\u003e s_a = 8 km/h. Ratio s_a : s_b = 4:5 =\u003e s_b = 10 km/h. Upstream in beta = 24 - 10 = 14 km/h. Distance in 6 hours = 14Ã—6 = 84 km.",
                             "source":  "boat.pdf pages 50-51",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-141",
                             "text":  "Current flows at 20 km/h. Craft speed in still water is 2.5 times current. Craft travels x km downstream in 4 hours. Calculate total time to traverse (x+50) km upstream.",
                             "options":  [
                                             "A) 11 hr",
                                             "B) 13 hr",
                                             "C) 55 hr",
                                             "D) 19 hr",
                                             "E) None of these"
                                         ],
                             "correct":  "A",
                             "chapter":  "boats-stream",
                             "difficulty":  "medium",
                             "explanation":  "Current = 20, craft = 50. Downstream = 70, so x = 70Ã—4 = 280 km. Upstream = 30 km/h. Time for 280+50 = 330 km upstream = 330/30 = 11 hours.",
                             "source":  "boat.pdf page 51",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-142",
                             "text":  "Proportion of boat\u0027s velocity in still water to current is 7:4. Boat takes 14 hours to travel 440 km downstream and 90 km upstream. Find speed of boat against current.",
                             "options":  [
                                             "A) 35 km/h",
                                             "B) 20 km/h",
                                             "C) 55 km/h",
                                             "D) 70 km/h",
                                             "E) 15 km/h"
                                         ],
                             "correct":  "E",
                             "chapter":  "boats-stream",
                             "difficulty":  "easy",
                             "explanation":  "Let boat = 7x, current = 4x. Downstream = 11x, upstream = 3x. Time = 440/11x + 90/3x = 40/x + 30/x = 70/x = 14 =\u003e x = 5. Upstream speed = 3Ã—5 = 15 km/h.",
                             "source":  "boat.pdf page 51",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-143",
                             "text":  "Velocity of craft with current is 25% greater than in calm water. Craft can navigate 90 km against and 120 km with current in 9 hours. Find total time for 180 km both against and with current.",
                             "options":  [
                                             "A) 16 hr",
                                             "B) 14 hr",
                                             "C) 10 hr",
                                             "D) 22 hr",
                                             "E) None of these"
                                         ],
                             "correct":  "A",
                             "chapter":  "boats-stream",
                             "difficulty":  "hard",
                             "explanation":  "Let boat = b, downstream = 1.25b =\u003e stream = 0.25b. Upstream = 0.75b. Time = 90/(0.75b) + 120/(1.25b) = 120/b + 96/b = 216/b = 9 =\u003e b = 24 km/h. Downstream = 30, upstream = 18. Time for 180 km both = 180/30 + 180/18 = 6 + 10 = 16 hours.",
                             "source":  "boat.pdf pages 51-52",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-144",
                             "text":  "Boat X travels with speed ratio 7:4 relative to stream. Takes 11 hours to navigate 330 km upstream. How long will Boat Y (same speed) take to cover 550 km downstream?",
                             "options":  [
                                             "A) 5 hr",
                                             "B) 7 hr",
                                             "C) 6 hr",
                                             "D) 9 hr",
                                             "E) None of these"
                                         ],
                             "correct":  "A",
                             "chapter":  "boats-stream",
                             "difficulty":  "easy",
                             "explanation":  "Let boat = 7x, stream = 4x. Upstream = 3x = 330/11 = 30 =\u003e x = 10. Boat = 70, stream = 40. Downstream = 110 km/h. Time for 550 km = 550/110 = 5 hours.",
                             "source":  "boat.pdf page 52",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-145",
                             "text":  "A vessel journeys downstream and returns in 14 hours. Aggregate speed of upstream and downstream is 70 km/h. Vessel speed in placid waters surpasses stream by 600%. Calculate distance upstream.",
                             "options":  [
                                             "A) 240 km",
                                             "B) 480 km",
                                             "C) 440 km",
                                             "D) 520 km",
                                             "E) None of these"
                                         ],
                             "correct":  "A",
                             "chapter":  "boats-stream",
                             "difficulty":  "hard",
                             "explanation":  "Let boat = b, stream = s. b = 7s (since 600% more means b = s + 6s = 7s). Downstream = 8s, upstream = 6s. Sum = 14s = 70 =\u003e s = 5, b = 35. Downstream = 40, upstream = 30. Let distance = d. d/40 + d/30 = 7d/120 = 14 =\u003e d = 240 km.",
                             "source":  "boat.pdf page 52",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-146",
                             "text":  "Speed of vessel downstream exceeds upstream by 20 km/h. Vessel requires 4 hours to travel (x+20) km with current and (x-10) km against current. Ratio of vessel speed in still water to current is 5:2. Find x.",
                             "options":  [
                                             "A) 43",
                                             "B) 44",
                                             "C) 34",
                                             "D) 65",
                                             "E) None of these"
                                         ],
                             "correct":  "A",
                             "chapter":  "boats-stream",
                             "difficulty":  "hard",
                             "explanation":  "Let vessel = 5y, current = 2y. Downstream = 7y, upstream = 3y. Difference = 4y = 20 =\u003e y = 5. Downstream = 35, upstream = 15. Time = (x+20)/35 + (x-10)/15 = 4 =\u003e Multiply 105: 3(x+20) + 7(x-10) = 420 =\u003e 3x+60+7x-70=420 =\u003e 10x-10=420 =\u003e 10x=430 =\u003e x=43.",
                             "source":  "boat.pdf page 53",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-147",
                             "text":  "Time for vessel to travel a particular distance on its own is 8 hours more than time to cover same distance downstream. Ratio of vessel speed in still water to current is 7:2. Calculate duration for vessel to navigate this distance downstream.",
                             "options":  [
                                             "A) 28 hr",
                                             "B) 29 hr",
                                             "C) 32 hr",
                                             "D) 36 hr",
                                             "E) None of these"
                                         ],
                             "correct":  "A",
                             "chapter":  "boats-stream",
                             "difficulty":  "hard",
                             "explanation":  "Let vessel = 7x, current = 2x. Downstream = 9x, upstream = 5x. Let distance = d. Time downstream = d/9x, time in still water = d/7x, time upstream = d/5x. Given d/5x - d/9x = 8 =\u003e (9d-5d)/45x = 4d/45x = 8 =\u003e d/x = 90. Time downstream = d/9x = 90/9 = 10 hours? That gives 10, not 28. There\u0027s confusion. If \"on its own\" means still water, then d/7x - d/9x = 8 =\u003e (9d-7d)/63x = 2d/63x = 8 =\u003e d/x = 252. Time downstream = 252/9 = 28 hours.",
                             "source":  "boat.pdf page 53",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-148",
                             "text":  "Ratio of upstream speed to downstream speed is 3:7. Time to cover 150 km upstream and 350 km downstream is 20 hours. Find speed of boat in still water.",
                             "options":  [
                                             "A) 10 km/h",
                                             "B) 35 km/h",
                                             "C) 15 km/h",
                                             "D) 40 km/h",
                                             "E) 25 km/h"
                                         ],
                             "correct":  "E",
                             "chapter":  "boats-stream",
                             "difficulty":  "easy",
                             "explanation":  "Let upstream = 3x, downstream = 7x. Time = 150/3x + 350/7x = 50/x + 50/x = 100/x = 20 =\u003e x = 5. Upstream = 15, downstream = 35. Boat = (15+35)/2 = 25 km/h.",
                             "source":  "boat.pdf page 54",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-149",
                             "text":  "Upstream speed of boat is 7 km/h and stream speed is 2 km/h. Time to cover X km downstream is 22 hours and upstream distance is 38 more than downstream distance. Find time taken to cover upstream distance.",
                             "options":  [
                                             "A) 55 hr",
                                             "B) 45 hr",
                                             "C) 65 hr",
                                             "D) 85 hr",
                                             "E) None of these"
                                         ],
                             "correct":  "A",
                             "chapter":  "boats-stream",
                             "difficulty":  "hard",
                             "explanation":  "Boat = upstream + stream = 7+2=9 km/h. Downstream = 9+2=11 km/h. X/11 = 22 =\u003e X = 242 km. Upstream distance = X+38 = 280 km. Upstream speed = 7 km/h. Time = 280/7 = 40 hours? Actually upstream speed is given as 7 km/h directly. Time = 280/7 = 40 hours. Not in options. Let me recalc: Boat speed = 9, stream=2, upstream=7, downstream=11. X=242, upstream dist=280, time=280/7=40. PDF answer shows 55. Something off.",
                             "source":  "boat.pdf page 54",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         },
                         {
                             "id":  "boat-150",
                             "text":  "A boat covers (x+20) km downstream and x km upstream in 4 hours. Stream speed is 20% of boat speed in calm water. Boat covers 250 km in 5 hours in still water. Find x.",
                             "options":  [
                                             "A) 87",
                                             "B) 85",
                                             "C) 88",
                                             "D) 66",
                                             "E) None of these"
                                         ],
                             "correct":  "A",
                             "chapter":  "boats-stream",
                             "difficulty":  "medium",
                             "explanation":  "Boat speed in still water = 250/5 = 50 km/h. Stream = 10 km/h. Downstream = 60, upstream = 40. Time = (x+20)/60 + x/40 = 4 =\u003e Multiply 120: 2(x+20) + 3x = 480 =\u003e 2x+40+3x=480 =\u003e 5x=440 =\u003e x=88.",
                             "source":  "boat.pdf pages 54-55",
                             "createdAt":  1780066937176,
                             "importBatch":  "Import 29 May, 08:32 pm",
                             "timesSolved":  0,
                             "timesCorrect":  0,
                             "consecutiveCorrect":  0,
                             "status":  "NEW",
                             "isArchived":  false
                         }
                     ]
};
